mytest:
  test111
server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql:///db2019?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root

eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka  #单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版本 都进行注册
    register-with-eureka: true  #默认为true
    fetch-registry: true    #默认true ,集群环境必须为true
  instance:
    instance-id: payment8001  #修改实例名字
    prefer-ip-address: true  #访问路径可以显示ip地址,左下角显示

    #Eureka 客户端先服务端发送心跳时间间隔  单位为秒(默认30)  反向案例 实现自我保护失效
    lease-renewal-interval-in-seconds: 1
    #Eureka 服务端在收到最后一次心跳等待时间上限. 单位为秒(90) 超时剔除服务
    lease-expiration-duration-in-seconds: 2

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.cssl.springcloud.entities    # 所有Entity别名类所在包
